[package]
name = "api_gen"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
publish = false

[dependencies]
bindgen = "0.64.0"
